default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: message_me_development

test:
  <<: *default
  database: message_me_test

production:
  <<: *default
  database: message_me_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
